name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.3', '7.4', '8.0', '8.1', '8.2']
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - uses: actions/checkout@v3

      - if: ${{ matrix.php <= 8.1 }}
        run: rm composer.lock

      - name: Install PHP dependencies
        run: make vendor

      - name: Build
        run: make

      - name: Run check
        env:
          PHPUNITFLAGS: --coverage-clover=cov.xml
        run: make check

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: cov.xml
