name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        php: ['7.3', '7.4', '8.0', '8.1', '8.2', '8.3']
        include:
          - os: windows-latest
            php: '8.3'
          - os: macos-latest
            php: '8.3'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - uses: actions/checkout@v4

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
        shell: bash

      - uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ matrix.php }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.php }}-composer-

      - if: ${{ matrix.php < 8.1 }}
        run: rm composer.lock

      - name: Install PHP dependencies
        run: make vendor

      - name: Build
        run: make

      - name: Run test
        env:
          PHPUNITFLAGS: --coverage-clover=cov.xml
        run: make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: cov.xml

  analyse:
    runs-on: ubuntu-latest
    steps:
      - name: Runner info
        run: |
          php --version

      - uses: actions/checkout@v4

      - name: Get PHP version
        id: php
        run: echo "version=$(php -r 'echo PHP_VERSION;' | cut -d. -f1-2)" >> $GITHUB_OUTPUT
        shell: bash

      - name: Get Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
        shell: bash

      - uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-${{ steps.php.outputs.version }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.php.outputs.version }}-composer-

      - name: Install PHP dependencies
        run: make vendor

      - name: Run analyse
        run: make analyse
