name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        php: ['7.3', '7.4', '8.0', '8.1', '8.2']
        include:
          - os: windows-latest
            php: '8.2'
          - os: macos-latest
            php: '8.2'
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: xdebug

      - uses: actions/checkout@v3

      - if: ${{ matrix.php < 8.1 }}
        run: rm composer.lock

      - name: Install PHP dependencies
        run: make vendor

      - name: Build
        run: make

      - name: Run test
        env:
          PHPUNITFLAGS: --coverage-clover=cov.xml
        run: make test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          files: cov.xml

  analyse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install PHP dependencies
        run: make vendor

      - name: Run analyse
        run: make analyse
