name: linkcheck

on:
  schedule:
    - cron: '33 3 * * 1'
  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Python dependencies
        run: pip install -r docs/requirements.txt
      - name: Install PHP dependencies
        run: make vendor
      - name: Run linkcheck
        run: make docs BUILDER=linkcheck
